### ISSUE TITLE
frpc配置文件编辑

### ISSUE THREAD

**Issue by Nova-Squ1** [Muska-Ami/NyaLCF#1]
能不能加个自定义配置文件啊（_frpc.ini_）
不能自定义没法编辑_proxy_protocol_ 服务器需要它返回真实ip
**暴风哭泣** 
:)tks

**Comment by Muska-Ami** [comment]
当前思路：
1. 用户选择使用高级启动模式
2. 请求服务端生成的frpc.ini
3. 写入${support_path}/frpc/proxy_configs/${proxy_id}.ini
4. 内置文本编辑器，用户可选择编辑${proxy_id}.ini
5. 启动时检测自定义配置是否存在，存在则不使用简易启动

**Comment by Muska-Ami** [comment]
已实现，请下载最新版本体验
