### ISSUE TITLE
[FEAT]: 控制台信息过长

### ISSUE THREAD

**Issue by Nova-Squ1** [Muska-Ami/NyaLCF#102]
### 问前检查

- [X] 我确保本功能尚未加入
- [X] 我确保没有其他 Issue 提出此功能

### 功能描述

建议在关闭所有进程后清理_控制台_的信息记录喵（或者添加个手动清理？
应该能实现吧？我是_彩笔_

**Comment by Muska-Ami** [comment]
其实超过200行会自动截断，不过加个按钮这个我也有想过

**Comment by ltzXiaoYanMo** [comment]
@Muska-Ami 你每次遇到问题先Assign我是吧
