### ISSUE TITLE
[BUG]: 开启隧道会闪退（可能为frpc目录不正确导致的）

### ISSUE THREAD

**Issue by SDCOM-0415** [Muska-Ami/NyaLCF#105]
### 问前检查

- [X] 我在提问之前，已经自己排查过问题
- [X] 我确保我已经搜索了相关资料，但仍无法解决
- [X] 我确保这个 BUG 未曾被报告过
- [X] 我确保这个 BUG 在最新版本可复现
- [X] 我确保我已经熟记[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)

### 问题描述&复现过程

启动隧道会闪退，根据终端的报告来看是没有正常的指定到frpc的位置
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/50c08071-1b4d-4c71-a952-42bdbbcadd8e)
而且经过系统目录的查找也确实没有找到那个frpc的目录
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/752fac3d-df4f-4ff9-a905-620aef64c5c5)
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/01580bac-de7c-4a65-8c56-f64b1b8e9606)
在仔细寻找过了以后发现frpc实际是在macOS"资源库"其中的软件文件存放位置的Data>Library>Caches的地方
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/4071d610-047b-4363-8eec-d7c03f779986)
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/c49d451c-a5e3-4be1-b3ab-0768a3ba1f52)
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/c53c94d4-00b3-453b-b7e9-2fd5349c29b2)

### 版本

v0.1.7+5 for macOS

### 运行日志

```sh
希望你也能知道macOS中的${SupportPath}在哪里，反正我是没找到
```

**Comment by Muska-Ami** [comment]
Caches 中的frpc理应被复制到Application Support文件夹中，此处未正常复制原因暂时不明确

**Comment by Muska-Ami** [comment]
请尝试赋予Frpc可执行权限

**Comment by SDCOM-0415** [comment]
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/c9c8d45a-66d1-4042-8b4c-3abd235a8633)
已经尝试赋予权限了，且指定Frpc位置也没有作用
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/c6c5c728-aae3-48e3-ba79-be2db522ea15)
推荐在设置页就可以改文件目录，然后就是依旧存在目录问题

**Comment by SDCOM-0415** [comment]
再补一条，使用终端尝试直接运行会直接提示没有这个条目
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/bb92977f-d94d-458c-b042-55d9808798bd)

**Comment by SDCOM-0415** [comment]
版本已经更新到了0.1.8
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/9f95146b-3753-441d-9f5e-0499334849ab)

**Comment by Muska-Ami** [comment]
尚不清楚原因，可能是在沙盒运行的问题

**Comment by Muska-Ami** [comment]
关于路径指定: 定义环境变量并非每个平台都一样，该实例仅供参考

**Comment by Muska-Ami** [comment]
根据相关包说明，该问题由 `MacOS OSX Sandbox` 导致，现已设置禁用沙盒，请尝试 `dev` 分支最新构建

**Comment by SDCOM-0415** [comment]
依旧不行
依旧是运行就闪退
半个日志：
`2024-03-22 11:56:16.620 nyanana[5931:39859] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.638 (+0:00:00.000087)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Checking update...
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.642 (+0:00:00.004211)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "GetMaterialController" has been created
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.642 (+0:00:00.004505)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "GetMaterialController" has been initialized
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.642 (+0:00:00.004662)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "FrpcController" has been created
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.642 (+0:00:00.004782)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "FrpcController" has been initialized
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.643 (+0:00:00.004899)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "_HC" has been created
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.643 (+0:00:00.004978)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "_HC" has been initialized
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.643 (+0:00:00.005053)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "UserController" has been created
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.643 (+0:00:00.005126)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "UserController" has been initialized
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.653 (+0:00:00.014838)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Check token if is valid
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.658 (+0:00:00.020732)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Check token if is valid
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.819 (+0:00:00.181420)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Refresh user info
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.829 (+0:00:00.191558)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Refresh user info
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.963 (+0:00:00.325347)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ type 'Null' is not a subtype of type 'int'
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.986 (+0:00:00.348486)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "DPanelController" has been created
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.986 (+0:00:00.348696)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "DPanelController" has been initialized
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.987 (+0:00:00.348937)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "ConsoleController" has been created
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.987 (+0:00:00.349015)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "ConsoleController" has been initialized
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.987 (+0:00:00.349120)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Get broadcast announcement
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:16.990 (+0:00:00.352009)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ type 'Null' is not a subtype of type 'int'
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:17.327 (+0:00:00.689334)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Get common announcement
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:17.853 (+0:00:01.214922)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ You are running latest version.
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:58.174 (+0:00:41.536032)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ OPEN DIALOG 614942559
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:56:59.749 (+0:00:43.111010)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ CLOSE DIALOG 614942559
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:57:01.659 (+0:00:45.020972)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ OPEN DIALOG 299293597
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:57:02.574 (+0:00:45.936170)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ CLOSE DIALOG 299293597
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:57:08.123 (+0:00:51.484863)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "ProxiesController" has been created
flutter: └───────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────
flutter: │ 11:57:08.123 (+0:00:51.485011)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Instance "ProxiesController" has been initialized
flutter: └───────────────────────────────────────────────────────────`
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/3981a678-08b1-41f2-9931-8cdb2ce7042b)
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/7b6b1260-1047-437c-8586-a1c1d39bf7f3)

**Comment by SDCOM-0415** [comment]
补充说明：该日志为直接获取终端的输出，版本为最新构建版本，frpc在正确的目录下

**Comment by SDCOM-0415** [comment]
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/2ceb91b0-c8f1-4446-85e1-5e1d665649eb)
[2024-03-22 12-05-27.mp4.zip](https://github.com/Muska-Ami/NyaLCF/files/14717175/2024-03-22.12-05-27.mp4.zip)
（自行解压压缩包查看视频文件）

**Comment by Muska-Ami** [comment]
@SDCOM-0415 permission denied的话，尝试重新赋予frpc执行权限试试
