### ISSUE TITLE
[FEAT]: 去除macOS红绿灯

### ISSUE THREAD

**Issue by SDCOM-0415** [Muska-Ami/NyaLCF#106]
### 问前检查

- [X] 我确保本功能尚未加入
- [X] 我确保没有其他 Issue 提出此功能

### 功能描述

去除一下macOS软件红绿灯，会挡住菜单，可以参考一下hmcl
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/af39ef8e-4d74-4588-8d1d-ee32b2bc19dc)
![image](https://github.com/Muska-Ami/NyaLCF/assets/127208666/d2ed700b-5745-40f3-bcee-400e59255de6)

**Comment by Muska-Ami** [comment]
请尝试 ![8220829980](https://github.com/Muska-Ami/NyaLCF/actions/runs/8220829980)
