### ISSUE TITLE
[FEAT]: 最大化控制台

### ISSUE THREAD

**Issue by Muska-Ami** [Muska-Ami/NyaLCF#133]
### 问前检查

- [X] 我确保本功能尚未加入
- [X] 我确保没有其他 Issue 提出此功能

### 功能描述

可将控制台直接放大至占满整个应用程序

**Comment by ltzXiaoYanMo** [comment]
这...这必要吗🤔？

**Comment by Muska-Ami** [comment]
> 这...有必要吗🤔？

它都是个终端了你就让着点它吧

**Comment by ltzXiaoYanMo** [comment]
> > 这...有必要吗🤔？
> 
> 它都是个终端了你就让着点它吧

好好好（
