### ISSUE TITLE
[FEAT]: 支持Ubuntu20.04LTS

### ISSUE THREAD

**Issue by ALEXsun0** [Muska-Ami/NyaLCF#135]
### 问前检查

- [X] 我确保本功能尚未加入
- [X] 我确保没有其他 Issue 提出此功能

### 功能描述

> # nyanana
> nyanana: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by nyanana)
> # ldd --version
> ldd (Ubuntu GLIBC 2.31-0ubuntu9.15) 2.31
> Copyright (C) 2020 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> Written by Roland McGrath and Ulrich Drepper.

要升级GLIBC的话好像就只能更新系统了吧，有没有在Ubuntu20.04安装的方案
桌面版打不开

**Comment by Muska-Ami** [comment]
请参考: https://blog.csdn.net/TaviaHong/article/details/119000431
升级libc版本
