### ISSUE TITLE
[FEAT]: 提供用于 Linux 服务器的命令行工具

### ISSUE THREAD

**Issue by JooDye** [Muska-Ami/NyaLCF#155]
### 问前检查

- [X] 我确保本功能尚未加入
- [X] 我确保没有其他 Issue 提出此功能

### 功能描述

```
 nyanana 

(nyanana:3333): Gtk-WARNING **: 11:49:32.513: cannot open display: 
```

**Comment by Muska-Ami** [comment]
命令行级别我们更推荐使用PureApp手动部署，不过后续会考虑添加，目前没有合适的tui框架所以一直没有做

**Comment by Muska-Ami** [comment]
https://pub.dev/packages/tui

有空会把相关包 fork 移植到 Dart 2 平台，耗时较长，急需相关功能建议使用 [PureApp](https://github.com/LoCyan-Team/LoCyanFrpPureApp)
