### ISSUE TITLE
[FEAT]: 可否开发无GUI的版本？

### ISSUE THREAD

**Issue by RCUTANF** [Muska-Ami/NyaLCF#157]
### 问前检查

- [X] 我确保本功能尚未加入
- [X] 我确保没有其他 Issue 提出此功能

### 功能描述

当前UI确实做的不错值得夸赞，但是我们的小服务器跑的是无gui的Ubuntu服务端，这给我带来很大困扰。简易启动命令虽然有效，但是这无法像现有版本一样同步账号进行管理。可否制作一个类似管理面版这样的方案（比如宝塔），或者只是实现一个基本的本地cli管理方案（如cpolar）？

**Comment by Muska-Ami** [comment]
Please see #155

由于尚未进行 dart tui 的移植操作，所以开发周期可能较长
建议先使用 PureApp 并写入系统服务来管理

**Comment by Muska-Ami** [comment]
CLI版本已经开始开发，最终没有打算开发Terminal UI版本

**Comment by TSaltedfishKing** [comment]
也许这些内容能暂时帮助到你
[GUI Apps without a graphical desktop](https://superuser.com/questions/503343/gui-apps-without-a-graphical-desktop)
[Can I have Graphics on Linux without a desktop manager?](https://superuser.com/questions/493319/can-i-have-graphics-on-linux-without-a-desktop-manager)

**Comment by Muska-Ami** [comment]
#169

**Comment by Muska-Ami** [comment]
由于我个人的原因，可能没有精力维护CLI版本，更多相关内容更新可能延迟
