### ISSUE TITLE
[FEAT]: NyaLCF macOS 版本添加开发者签名

### ISSUE THREAD

**Issue by SDCOM-0415** [Muska-Ami/NyaLCF#161]
### 问前检查

- [X] 我在提问之前，已经自己排查过问题
- [X] 我确保我已经搜索了相关资料，但仍无法解决
- [X] 我确保这个 BUG 未曾被报告过
- [X] 我确保这个 BUG 在最新版本可复现
- [X] 我确保我已经熟记[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)

### 问题描述&复现过程

![6edb31c27822c312fb4a5f6acb16ff20](https://github.com/user-attachments/assets/a6d00213-024f-4d01-b81b-fabe23b15d6e)
打开后就会提示，macOS sequoia不能修改为任何来源，必须进入隐私与安全性手动打开
![df80eee2cbfba11e49dc38e82a1ce3f8](https://github.com/user-attachments/assets/c80b172b-8e19-41f3-becf-494424df80e9)

### 版本

v0.1.10+1

### 运行日志

```sh
这种东西Apple是不会给你日志看的
```

**Comment by ltzXiaoYanMo** [comment]
我们这边没有资金给Apple每年送99美金😇
![QQ_1721493118315](https://github.com/user-attachments/assets/77b68778-4090-4442-ae23-7bd6343a159a)

**Comment by Shiroiame-Kusu** [comment]
你可以选择右键app点击打开试试

**Comment by SDCOM-0415** [comment]
> 我们这边没有资金给Apple每年送99美金😇 ![QQ_1721493118315](https://private-user-images.githubusercontent.com/115706851/350706768-77b68778-4090-4442-ae23-7bd6343a159a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzkyMzQsIm5iZiI6MTcyMjkzODkzNCwicGF0aCI6Ii8xMTU3MDY4NTEvMzUwNzA2NzY4LTc3YjY4Nzc4LTQwOTAtNDQ0Mi1hZTIzLTdiZDYzNDNhMTU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMDA4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjJkZjAwNGE5YjM3Yjk1ZmIzZDY4NDFkOWNhNzhlZmRkZTAwYWRkMzcwYmVkZTY0MzU4OWE4N2NkNTUxZTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u6s7u2feP7BlAN_4VCkUYbXnMVcYJyF_QBChqtuBSEA)

bro那只是给上架App Store的开发者用的，线下分发免费的bro
☠️☠️☠️

**Comment by LxHTT** [comment]
macOS App 大致被认定为三类：
- App Store App  
- 受信第三方开发者App  
- 其他App  

目前NyaLCF应属于第三类，且没有足够资金购入证书。  

___

关于 macOS Sequoia `spctl` 被禁用导致的问题，您可参考以下文章进行修改：  

[MacOS 15 Sequoia 启用允许“任何来源”应用 - CNBlogs](https://www.cnblogs.com/qi-xmu/p/18298100)  

macOS Sequoia Beta 3以下版本的用户，可直接打开终端输入`sudo spctl --master-disable`，然后打开`设置`-`隐私与安全性`-`安全性`进行更改。

**Comment by LxHTT** [comment]
> macOS App 大致被认定为三类：
> - App Store App  
> - 受信第三方开发者App  
> - 其他App  
> 
> 目前NyaLCF应属于第三类，且没有足够资金购入证书。  
> 
> ___
> 
> 关于 macOS Sequoia `spctl` 被禁用导致的问题，您可参考以下文章进行修改：  
> 
> [MacOS 15 Sequoia 启用允许“任何来源”应用 - CNBlogs](https://www.cnblogs.com/qi-xmu/p/18298100)  
> 
> macOS Sequoia Beta 3以下版本的用户，可直接打开终端输入`sudo spctl --master-disable`，然后打开`设置`-`隐私与安全性`-`安全性`进行更改。

ADP分发的证书其实与从第三方购买的证书大差不差，都要使用`codesign`签名

**Comment by ltzXiaoYanMo** [comment]
> > 我们这边没有资金给Apple每年送99美金😇 ![QQ_1721493118315](https://private-user-images.githubusercontent.com/115706851/350706768-77b68778-4090-4442-ae23-7bd6343a159a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzkyMzQsIm5iZiI6MTcyMjkzODkzNCwicGF0aCI6Ii8xMTU3MDY4NTEvMzUwNzA2NzY4LTc3YjY4Nzc4LTQwOTAtNDQ0Mi1hZTIzLTdiZDYzNDNhMTU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMDA4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjJkZjAwNGE5YjM3Yjk1ZmIzZDY4NDFkOWNhNzhlZmRkZTAwYWRkMzcwYmVkZTY0MzU4OWE4N2NkNTUxZTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u6s7u2feP7BlAN_4VCkUYbXnMVcYJyF_QBChqtuBSEA)
> 
> bro那只是给上架App Store的开发者用的，线下分发免费的bro
> ☠️☠️☠️

你知道吗，那个官网明摆着就是写的证书，你告诉我线下免费你能先签一张然后PR Welcome吗

**Comment by ltzXiaoYanMo** [comment]
目前无法解决，现Close

**Comment by Muska-Ami** [comment]
Pined for documentation.

**Comment by Muska-Ami** [comment]
@ltzXiaoYanMo Please communicate with other friendly.
If need, please read GitHub Community Guidelines.
