### ISSUE TITLE
[FEAT]: 添加arm64 liunx

### ISSUE THREAD

**Issue by fishcpy** [Muska-Ami/NyaLCF#186]
### 问前检查

- [X] 我确保本功能尚未加入
- [X] 我确保没有其他 Issue 提出此功能

### 功能描述

arm64 liunx

**Comment by Muska-Ami** [comment]
由于上游 Flutter 并未发布对 arm64 Linux 的支持，无法对软件适配 arm64 架构的基于 Linux 的操作系统
