### ISSUE TITLE
[BUG]: 托盘菜单触发无效

### ISSUE THREAD

**Issue by Muska-Ami** [Muska-Ami/NyaLCF#189]
### 问前检查

- [X] 我在提问之前，已经自己排查过问题
- [X] 我确保我已经搜索了相关资料，但仍无法解决
- [X] 我确保这个 BUG 未曾被报告过
- [X] 我确保这个 BUG 在最新版本可复现
- [X] 我确保我已经熟记[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)

### 问题描述&复现过程

托盘菜单无法进行任何操作
See here: leanflutter/tray_manager#53

### 版本

0.2.3 (+0)

### 运行日志

```sh
No any log here, this is an upsteam bug
```

**Comment by CodeStar999** [comment]
托盘无效，你是怎么解决的呢？

**Comment by Muska-Ami** [comment]
> 托盘无效，你是怎么解决的呢？

目前没有找到解决方案，只是开着Issue xd

**Comment by CodeStar999** [comment]
我使用了system_tray库，就彻底解决了

**Comment by Muska-Ami** [comment]
有空我去看一下，感谢你提供的方案
