### ISSUE TITLE
Arm64 support?

### ISSUE THREAD

**Issue by xrh0905** [Muska-Ami/NyaLCF#33]
```
root@rpi:/opt# apt install ./nyalcf-0.1.1+0.1.1-linux.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'nyanana:amd64' instead of './nyalcf-0.1.1+0.1.1-linux.deb'
The following NEW packages will be installed:
  nyanana:amd64
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/28.3 MB of archives.
After this operation, 6762 kB of additional disk space will be used.
Get:1 /opt/nyalcf-0.1.1+0.1.1-linux.deb nyanana amd64 0.1.1 [28.3 MB]
dpkg: error processing archive /opt/nyalcf-0.1.1+0.1.1-linux.deb (--unpack):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 /opt/nyalcf-0.1.1+0.1.1-linux.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Muska-Ami** [comment]
呃呃，没有考虑arm64打包，会想办法打包的

**Comment by xrh0905** [comment]
感谢如此快速的回复。
看起来项目用了框架，迁移应该不是特别难。
树莓派的用户不少，这个应该还是有必要的。

**Comment by Muska-Ami** [comment]
> 感谢如此快速的回复。
> 看起来项目用了框架，迁移应该不是特别难。
> 树莓派的用户不少，这个应该还是有必要的。

主要是暂时没有思路如何在GitHub Actions中使用Arm架构的系统，正在查文档

**Comment by Muska-Ami** [comment]
https://github.com/Muska-Ami/NyaLCF/actions/runs/7512569913

我重写了Actions脚本，请尝试此构建是否可用

**Comment by Muska-Ami** [comment]
@ltzXiaoYanMo 你有什么头绪吗

**Comment by ltzXiaoYanMo** [comment]
~~首先你搜索绝对能得出答案~~<br>
这并非假话，因Linux系统的开源性使你大多数的问题都能解决。<br>
我姑且认为是`编译参数`和`Actions`的配置原因。但悲报是看到此条消息的时候我在挺困的（<br>
等一会我会修复的，感谢你对NyaLCF的支持！

**Comment by Muska-Ami** [comment]
> ~~首先你搜索绝对能得出答案~~<br>
> 这并非假话，因Linux系统的开源性使你大多数的问题都能解决。<br>
> 我姑且认为是`编译参数`和`Actions`的配置原因。但悲报是看到此条消息的时候我在挺困的（<br>
> 等一会我会修复的，感谢你对NyaLCF的支持！

我查了一下似乎打包工具不支持，得先魔改打包工具

**Comment by Shiroiame-Kusu** [comment]
开台arm64手动打包（bushi

**Comment by ltzXiaoYanMo** [comment]
> > ~~首先你搜索绝对能得出答案~~<br>
> > 这并非假话，因Linux系统的开源性使你大多数的问题都能解决。<br>
> > 我姑且认为是`编译参数`和`Actions`的配置原因。但悲报是看到此条消息的时候我在挺困的（<br>
> > 等一会我会修复的，感谢你对NyaLCF的支持！
> 
> 我查了一下似乎打包工具不支持，得先魔改打包工具

```Actions
matrix architecture arm64
```
你试试把这个加上去

**Comment by Muska-Ami** [comment]
> > > ~~首先你搜索绝对能得出答案~~<br>
> > > 这并非假话，因Linux系统的开源性使你大多数的问题都能解决。<br>
> > > 我姑且认为是`编译参数`和`Actions`的配置原因。但悲报是看到此条消息的时候我在挺困的（<br>
> > > 等一会我会修复的，感谢你对NyaLCF的支持！
> > 
> > 我查了一下似乎打包工具不支持，得先魔改打包工具
> 
> ```Actions
> matrix architecture arm64
> ```
> 你试试把这个加上去

我试过了 打包工具里面写死了amd64 我打算有空改改

**Comment by ltzXiaoYanMo** [comment]
> > > > ~~首先你搜索绝对能得出答案~~<br>
> > > > 这并非假话，因Linux系统的开源性使你大多数的问题都能解决。<br>
> > > > 我姑且认为是`编译参数`和`Actions`的配置原因。但悲报是看到此条消息的时候我在挺困的（<br>
> > > > 等一会我会修复的，感谢你对NyaLCF的支持！
> > > 
> > > 我查了一下似乎打包工具不支持，得先魔改打包工具
> > 
> > ```Actions
> > matrix architecture arm64
> > ```
> > 你试试把这个加上去
> 
> 试过了，似乎没啥用

你去看看[MCSL2](https://github.com/MCSLTeam/MCSL2)的v2.2.2.2当时是怎么写的，我认为打包工具不太可能会把这个写死

**Comment by Muska-Ami** [comment]
@ltzXiaoYanMo 没写死，是获取系统的

**Comment by Muska-Ami** [comment]
@ltzXiaoYanMo 主要是没有arm64的runner

**Comment by Muska-Ami** [comment]
@ltzXiaoYanMo 在考虑TravisCI之类的其他CI/CD

**Comment by ltzXiaoYanMo** [comment]
> @ltzXiaoYanMo 在考虑TravisCI之类的其他CI/CD

~~《建议使用Gitee编译NyaLCF》~~

**Comment by xrh0905** [comment]
https://github.com/marketplace/actions/arm-runner

**Comment by Muska-Ami** [comment]
> https://github.com/marketplace/actions/arm-runner

这个不好配置Setup Flutter

**Comment by ltzXiaoYanMo** [comment]
> > https://github.com/marketplace/actions/arm-runner
> 
> 这个不好配置Setup Flutter

我去找台ARM服务器整自动编译得了（

**Comment by ltzXiaoYanMo** [comment]
本次测试已通过
