### ISSUE TITLE
样式优化与部分功能

### ISSUE THREAD

**Issue by SRY-CTB** [Muska-Ami/NyaLCF#34]
样式：公告的部分有点紧凑了，摘取重要部分（因为应该也没人会全部看完。还有就是圆角有点太圆了吧（仅个人认为
功能：
1.  登录：想第三方登录（QQ）
2. 下载frpc的部分，给个下载进度条
3.  反正就是想直接抛掉整个网站，直接启动器操作（嘿嘿

**Comment by ltzXiaoYanMo** [comment]
第二条Issue已经实现<br>
~~第一条能不能实现还是得看tx给不给面子~~<br>
这想法还挺好的，但加上单点登录目前还不清楚如何实现~~qwq~~

@Muska-Ami ，你有什么头绪吗（

**Comment by Muska-Ami** [comment]
第一个无法实现，因为回调URL写死了，目前LoCyanFrp未开放API接入

**Comment by Muska-Ami** [comment]
圆角度数来自Marterial Design 3设计，这个不做修改
