### ISSUE TITLE
支持深度链接启动

### ISSUE THREAD

**Issue by Muska-Ami** [Muska-Ami/NyaLCF#37]
如题，支持官网的深度链接调用启动
目前官方格式为
```
locyanfrp://:frp_token/:proxy_id
```

**Comment by Muska-Ami** [comment]
需要帮助，由于我不会CPP所以没法写接收的函数

**Comment by ltzXiaoYanMo** [comment]
```flutter
  void _parseDeepLink(String deepLink) {
    if (deepLink.isNotEmpty) {
      // 如果有深度链接，则提取数据
      Uri uri = Uri.parse(deepLink);
      String scheme = uri.scheme;
      if (scheme == 'locyanfrp') {
        // 如果是你指定的scheme（locyanfrp），则提取frp_token和proxy_id
        String frpToken = uri.pathSegments.isNotEmpty ? uri.pathSegments[0] : '';
        String proxyId = uri.pathSegments.length > 1 ? uri.pathSegments[1] : '';
        setState(() {
          _deepLinkData = 'FRP Token: $frpToken\nProxy ID: $proxyId';
        });
      }
    }
  }

**Comment by Muska-Ami** [comment]
> ```dart
>   void _parseDeepLink(String deepLink) {
>     if (deepLink.isNotEmpty) {
>       // 如果有深度链接，则提取数据
>       Uri uri = Uri.parse(deepLink);
>       String scheme = uri.scheme;
>       if (scheme == 'locyanfrp') {
>         // 如果是你指定的scheme（locyanfrp），则提取frp_token和proxy_id
>         String frpToken = uri.pathSegments.isNotEmpty ? uri.pathSegments[0] : '';
>         String proxyId = uri.pathSegments.length > 1 ? uri.pathSegments[1] : '';
>         setState(() {
>           _deepLinkData = 'FRP Token: $frpToken\nProxy ID: $proxyId';
>         });
>       }
>     }
>   }
> ```
> 我不知道这样行不行，放这看看吧（

这只是解析了Uri

**Comment by ltzXiaoYanMo** [comment]
> > ```dart
> >   void _parseDeepLink(String deepLink) {
> >     if (deepLink.isNotEmpty) {
> >       // 如果有深度链接，则提取数据
> >       Uri uri = Uri.parse(deepLink);
> >       String scheme = uri.scheme;
> >       if (scheme == 'locyanfrp') {
> >         // 如果是你指定的scheme（locyanfrp），则提取frp_token和proxy_id
> >         String frpToken = uri.pathSegments.isNotEmpty ? uri.pathSegments[0] : '';
> >         String proxyId = uri.pathSegments.length > 1 ? uri.pathSegments[1] : '';
> >         setState(() {
> >           _deepLinkData = 'FRP Token: $frpToken\nProxy ID: $proxyId';
> >         });
> >       }
> >     }
> >   }
> > ```
> > 我不知道这样行不行，放这看看吧（
> 
> 这只是解析了Uri

他能解析就是成功，怎么提取下辈子再说（

**Comment by Muska-Ami** [comment]
https://docs.flutter.dev/ui/navigation/deep-linking

**Comment by Muska-Ami** [comment]
https://pub.dev/packages/app_links

**Comment by Muska-Ami** [comment]
当前的实现感觉仍有不足，直接调用会新开一个启动器
进程，造成不必要的占用，应该给应用加一个RPC接口，先检测是否存在进程再判断是否应该启动GUI，否则直接使用现有进程执行操作

**Comment by ltzXiaoYanMo** [comment]
> 当前的实现感觉仍有不足，直接调用会新开一个启动器
> 进程，造成不必要的占用，应该给应用加一个RPC接口，先检测是否存在进程再判断是否应该启动GUI，否则直接使用现有进程执行操作

强制给自己添加难度是吧，那我先不卷了（？
