### ISSUE TITLE
自动检测NyaLCF是否为最新版本

### ISSUE THREAD

**Issue by ltzXiaoYanMo** [Muska-Ami/NyaLCF#54]
灵感来源：<br>
![Image_1705849313090.png](https://github.com/Muska-Ami/NyaLCF/assets/115706851/a9f14148-ab67-4bef-81fe-120f9deecac2)

目前可能可行的方案：<br>
向更新服务器发送HTTP GET消息获得最新版本进行比较。

**Comment by Muska-Ami** [comment]
有计划但是一直没写xd

**Comment by ltzXiaoYanMo** [comment]
> 有计划但是一直没写xd

这么玩是吧（

**Comment by Muska-Ami** [comment]
Done

**Comment by ltzXiaoYanMo** [comment]
先给你关了（？

**Comment by Muska-Ami** [comment]
呃呃关不关都行
