### ISSUE TITLE
MacOS 0.1.3 FRPC解压并未修复

### ISSUE THREAD

**Issue by molder3456** [Muska-Ami/NyaLCF#57]
<img width="328" alt="Screenshot 2024-01-24 at 09 05 43" src="https://github.com/Muska-Ami/NyaLCF/assets/151928209/3ae35890-1a2a-4877-8d06-f6b4ecd7f1e5">

用的是最新的MacOS 0.1.3版本
下载的是arm64/armv8的FRPC版本，下载时间很快。但是一直解压不了，已经快解压了半个小时了还是没有解压好。

求大佬帮助QAQ

**Comment by Muska-Ami** [comment]
能麻烦在Actions中下载最新的开发版重复步骤然后提供Support Directory中的run.log吗，感谢

**Comment by Muska-Ami** [comment]
与 #25 应该是一个问题

**Comment by Muska-Ami** [comment]
Tested by @shiftz300 ,fixed.
