### ISSUE TITLE
无法下载frpc(开vpn也下不了)

### ISSUE THREAD

**Issue by tdpclient** [Muska-Ami/NyaLCF#60]
版本0.1.5
![aa](https://github.com/Muska-Ami/NyaLCF/assets/108508282/338b423f-4b7b-45ba-b8bc-6e044aecfe41)

**Comment by Muska-Ami** [comment]
网络问题，请自查

**Comment by tdpclient** [comment]
不行，完全下不了，能不能手动按，我是windows10系统



小T
***@***.***

**Comment by Muska-Ami** [comment]
亲看到下载镜像源了吗 打开
