### ISSUE TITLE
[BUG]: MacBookAir M1 下载完后启动无法打开

### ISSUE THREAD

**Issue by LTtt456c** [Muska-Ami/NyaLCF#70]
### 问前检查

- [x] 我在提问之前，已经自己排查过问题
- [X] 我确保我已经搜索了相关资料，但仍无法解决
- [X] 我确保这个 BUG 未曾被报告过
- [X] 我确保这个 BUG 在最新版本可复现

### 问题描述&复现过程

系统环境：MacOS14.3
复现步骤:
1. [下载Nya LoCyanFrp! 乐青映射启动器
](https://nyalcf.1l1.icu)
2. 安装
3. 运行
4. 无法正常运行

### 版本

1.6

### 运行日志

```sh
没有
```

**Comment by ltzXiaoYanMo** [comment]
![Image_1707270758147.gif](https://github.com/Muska-Ami/NyaLCF/assets/115706851/aa3b08d4-da52-41b1-94c9-38f727d74cca)

你这想让我怎么解决

**Comment by Shiroiame-Kusu** [comment]
> > ![Image_1707270758147.gif](https://private-user-images.githubusercontent.com/115706851/302829322-aa3b08d4-da52-41b1-94c9-38f727d74cca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTg4ODQsIm5iZiI6MTcwNzI5ODU4NCwicGF0aCI6Ii8xMTU3MDY4NTEvMzAyODI5MzIyLWFhM2IwOGQ0LWRhNTItNDFiMS05NGM5LTM4ZjcyN2Q3NGNjYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTM2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTAxMmFjODVhMDYwZGY3MWVmMGZlODllMDE5YjM3NGFiMGQzNDg0ZDM0YjdjYmFkOWY0Zjk4MWRlZjEzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yoTfJDJyuARkN4qVDtxQdHp8i3r1fWDGYmx5B_Sjxss)
> >       
> >         [
> >           
> >             ![Image_1707270758147.gif](https://private-user-images.githubusercontent.com/115706851/302829322-aa3b08d4-da52-41b1-94c9-38f727d74cca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTg4ODQsIm5iZiI6MTcwNzI5ODU4NCwicGF0aCI6Ii8xMTU3MDY4NTEvMzAyODI5MzIyLWFhM2IwOGQ0LWRhNTItNDFiMS05NGM5LTM4ZjcyN2Q3NGNjYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTM2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTAxMmFjODVhMDYwZGY3MWVmMGZlODllMDE5YjM3NGFiMGQzNDg0ZDM0YjdjYmFkOWY0Zjk4MWRlZjEzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yoTfJDJyuARkN4qVDtxQdHp8i3r1fWDGYmx5B_Sjxss)
> >           
> >         ](https://private-user-images.githubusercontent.com/115706851/302829322-aa3b08d4-da52-41b1-94c9-38f727d74cca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTg4ODQsIm5iZiI6MTcwNzI5ODU4NCwicGF0aCI6Ii8xMTU3MDY4NTEvMzAyODI5MzIyLWFhM2IwOGQ0LWRhNTItNDFiMS05NGM5LTM4ZjcyN2Q3NGNjYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTM2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTAxMmFjODVhMDYwZGY3MWVmMGZlODllMDE5YjM3NGFiMGQzNDg0ZDM0YjdjYmFkOWY0Zjk4MWRlZjEzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yoTfJDJyuARkN4qVDtxQdHp8i3r1fWDGYmx5B_Sjxss)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/115706851/302829322-aa3b08d4-da52-41b1-94c9-38f727d74cca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTg4ODQsIm5iZiI6MTcwNzI5ODU4NCwicGF0aCI6Ii8xMTU3MDY4NTEvMzAyODI5MzIyLWFhM2IwOGQ0LWRhNTItNDFiMS05NGM5LTM4ZjcyN2Q3NGNjYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTM2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTAxMmFjODVhMDYwZGY3MWVmMGZlODllMDE5YjM3NGFiMGQzNDg0ZDM0YjdjYmFkOWY0Zjk4MWRlZjEzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yoTfJDJyuARkN4qVDtxQdHp8i3r1fWDGYmx5B_Sjxss)
> >         
> >        [ ![Image_1707270758147.gif](https://private-user-images.githubusercontent.com/115706851/302829322-aa3b08d4-da52-41b1-94c9-38f727d74cca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTg4ODQsIm5iZiI6MTcwNzI5ODU4NCwicGF0aCI6Ii8xMTU3MDY4NTEvMzAyODI5MzIyLWFhM2IwOGQ0LWRhNTItNDFiMS05NGM5LTM4ZjcyN2Q3NGNjYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTM2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTAxMmFjODVhMDYwZGY3MWVmMGZlODllMDE5YjM3NGFiMGQzNDg0ZDM0YjdjYmFkOWY0Zjk4MWRlZjEzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yoTfJDJyuARkN4qVDtxQdHp8i3r1fWDGYmx5B_Sjxss) ](https://private-user-images.githubusercontent.com/115706851/302829322-aa3b08d4-da52-41b1-94c9-38f727d74cca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTg4ODQsIm5iZiI6MTcwNzI5ODU4NCwicGF0aCI6Ii8xMTU3MDY4NTEvMzAyODI5MzIyLWFhM2IwOGQ0LWRhNTItNDFiMS05NGM5LTM4ZjcyN2Q3NGNjYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTM2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTAxMmFjODVhMDYwZGY3MWVmMGZlODllMDE5YjM3NGFiMGQzNDg0ZDM0YjdjYmFkOWY0Zjk4MWRlZjEzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yoTfJDJyuARkN4qVDtxQdHp8i3r1fWDGYmx5B_Sjxss)
> >       
> >         [
> >           
> >             ![Image_1707270758147.gif](https://private-user-images.githubusercontent.com/115706851/302829322-aa3b08d4-da52-41b1-94c9-38f727d74cca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTg4ODQsIm5iZiI6MTcwNzI5ODU4NCwicGF0aCI6Ii8xMTU3MDY4NTEvMzAyODI5MzIyLWFhM2IwOGQ0LWRhNTItNDFiMS05NGM5LTM4ZjcyN2Q3NGNjYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTM2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTAxMmFjODVhMDYwZGY3MWVmMGZlODllMDE5YjM3NGFiMGQzNDg0ZDM0YjdjYmFkOWY0Zjk4MWRlZjEzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yoTfJDJyuARkN4qVDtxQdHp8i3r1fWDGYmx5B_Sjxss)
> >           
> >         ](https://private-user-images.githubusercontent.com/115706851/302829322-aa3b08d4-da52-41b1-94c9-38f727d74cca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTg4ODQsIm5iZiI6MTcwNzI5ODU4NCwicGF0aCI6Ii8xMTU3MDY4NTEvMzAyODI5MzIyLWFhM2IwOGQ0LWRhNTItNDFiMS05NGM5LTM4ZjcyN2Q3NGNjYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTM2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTAxMmFjODVhMDYwZGY3MWVmMGZlODllMDE5YjM3NGFiMGQzNDg0ZDM0YjdjYmFkOWY0Zjk4MWRlZjEzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yoTfJDJyuARkN4qVDtxQdHp8i3r1fWDGYmx5B_Sjxss)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/115706851/302829322-aa3b08d4-da52-41b1-94c9-38f727d74cca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTg4ODQsIm5iZiI6MTcwNzI5ODU4NCwicGF0aCI6Ii8xMTU3MDY4NTEvMzAyODI5MzIyLWFhM2IwOGQ0LWRhNTItNDFiMS05NGM5LTM4ZjcyN2Q3NGNjYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTM2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTAxMmFjODVhMDYwZGY3MWVmMGZlODllMDE5YjM3NGFiMGQzNDg0ZDM0YjdjYmFkOWY0Zjk4MWRlZjEzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yoTfJDJyuARkN4qVDtxQdHp8i3r1fWDGYmx5B_Sjxss)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/115706851/302829322-aa3b08d4-da52-41b1-94c9-38f727d74cca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTg4ODQsIm5iZiI6MTcwNzI5ODU4NCwicGF0aCI6Ii8xMTU3MDY4NTEvMzAyODI5MzIyLWFhM2IwOGQ0LWRhNTItNDFiMS05NGM5LTM4ZjcyN2Q3NGNjYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTM2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTAxMmFjODVhMDYwZGY3MWVmMGZlODllMDE5YjM3NGFiMGQzNDg0ZDM0YjdjYmFkOWY0Zjk4MWRlZjEzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yoTfJDJyuARkN4qVDtxQdHp8i3r1fWDGYmx5B_Sjxss)
> > 你这想让我怎么解决
> 
> 去复现

没有成功复现，下一个
