### ISSUE TITLE
[BUG]: NYA_LCF_FRPC_PATH Not work

### ISSUE THREAD

**Issue by okobenoko** [Muska-Ami/NyaLCF#73]
### 问前检查

- [X] 我在提问之前，已经自己排查过问题
- [X] 我确保我已经搜索了相关资料，但仍无法解决
- [X] 我确保这个 BUG 未曾被报告过
- [X] 我确保这个 BUG 在最新版本可复现

### 问题描述&复现过程

OS: Arch linux

#!/bin/sh
if [ $1 ]; then
    export NYA_LCF_FRPC_PATH=$1
else
    export NYA_LCF_FRPC_PATH='/usr/bin/frpc'
fi

/usr/share/nyanana/nyanana
我正在给这个软件打AUR包（nyalcf-bin），并使用了上面的脚本，但是这个环境变量不起作用

### 版本

0.1.7-rc1

### 运行日志

```sh
没有和此环境变量有关的日志
```

**Comment by Muska-Ami** [comment]
这部分逻辑还在测试阶段，rc2还会有点改动，感谢跟踪进度，会尽快处理

**Comment by Muska-Ami** [comment]
这部分逻辑还在测试阶段，rc2还会有点改动，感谢跟踪进度，会尽快处理

**Comment by Muska-Ami** [comment]
Update: 提取了方法，由于上游API错误，暂时无法测试

**Comment by Muska-Ami** [comment]
Update: 已修复
![image](https://github.com/Muska-Ami/NyaLCF/assets/79651409/545c9299-bcd5-4f1e-b1e8-0d14a03999b8)
