### ISSUE TITLE
[FEAT]: 家人们谁懂啊，妹有菜单显示隧道是否连接成功一个个翻终端真的太虾头啦

### ISSUE THREAD

**Issue by BaiRuoQiu** [Muska-Ami/NyaLCF#78]
### 问前检查

- [X] 我确保本功能尚未加入
- [X] 我确保没有其他 Issue 提出此功能

### 功能描述

能不能在查看进程列表中添加显示当前隧道是否连接成功的状态信息啊，翻找太麻烦了，并且在断联后所有隧道也不会自动重连，每次连接失败多联几次又好了然而上述连接都需要手动还不如老版本一个个窗口的固定秒数每个通道都自动尝试重连，家人们谁懂啊，没人发现这个很反人类嘛？

**Comment by ltzXiaoYanMo** [comment]
我不懂，下一个

**Comment by ltzXiaoYanMo** [comment]
还有就是，发表Issue前请看[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)，你这几句给我整小脑萎缩了。⁧⁧

义演⁧‭顶针鉴定为玩原神玩的，当你的西瓜头去，别来GitHub乱投垃圾😅

**Comment by Jason25841** [comment]
我开始怀疑你是正经用GitHub的还是现充了

**Comment by daizihan233** [comment]
# [FEAT]: 家人们谁懂啊，妹有用正常人的思维写Issue真的太虾头啦
## 问前检查
 - [X] 我确保本功能尚未加入
 - [X] 我确保没有其他 Issue 提出此功能
## 功能描述
能不能在Issue正文中添加一些人能看得懂的且礼貌的信息啊，阅读理解太麻烦了，并且在发出后自己也不读一遍，每次都得让开发者先自行阅读理解几遍然而上述问题都是你在这个Issue中犯的错误还不如先去读一遍[《提问的智慧》](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)，家人们谁懂啊，没人发现这个很反人类嘛？

**Comment by BaiRuoQiu** [comment]
已经足够通俗易懂了还搁着看不懂搁着无效，还玩原神玩的，本想以幽默的方式交谈既然不喜就直说了：官网负载30%带宽没满，专挑人数少的隧道延迟时不时到500ms，之前c#那个还是啥端好好的还能每个通道都能自动重连，啊现在倒好天天掉线自己不连接有的时候莫名其妙断，之前单窗口好对应隧道，现在倒好全放在一个终端关键的隧道id和其他的字全一个颜色，根本不好对应，做不好建议直接回退之前版本，现在之前的版本也用不了真的无语了

**Comment by BaiRuoQiu** [comment]
最后感谢你们的评价。。。祝乐青越来越好吧。。。我如鲠在喉一时间不知道说什么了

**Comment by ltzXiaoYanMo** [comment]
义演顶针：没看提问的智慧导致的，没给你lock已经给你最大的仁慈了😅

**Comment by ltzXiaoYanMo** [comment]
这边建议当守旧派

**Comment by Muska-Ami** [comment]
你好Issue请尽量直切主题 你认为的幽默不是所有人都能接受的 你的幽默更多的让人感受到的是一种反讽。
提问之前，请看提问的智慧(https://lug.ustc.edu.cn/wiki/doc/smart-questions/)，谢谢

**Comment by Muska-Ami** [comment]
另外，本客户端本身与C\#客户端不是同一个语言开发，请你在发表Issue时考虑实际开发，Dart语言的STDLib并不好用，尽管作为用户你也没必要了解

**Comment by BaiRuoQiu** [comment]
那也不应当给予抨击或不切本题的“玩原神玩的”“现充”“投垃圾”这点是你们应当道歉的并且我本人有错在先向你们道歉，红豆泥私密马赛

**Comment by BaiRuoQiu** [comment]
> 另外，本客户端本身与C#客户端不是同一个语言开发，请你在发表Issue时考虑实际开发，Dart语言的STDLib并不好用，尽管作为用户你也没必要了解

是这样的，但作为功能性添加应当加入更简便直观的连接状态显示以及轮询的断联自动重连方便用户操作与维护

**Comment by Jason25841** [comment]
![Screenshot_20240215_005155.jpg](https://github.com/Muska-Ami/NyaLCF/assets/109329792/8701a88d-1e15-4039-b59f-40cd174315ee)

**Comment by BaiRuoQiu** [comment]
> ![Screenshot_20240215_005155.jpg](https://private-user-images.githubusercontent.com/109329792/304812705-8701a88d-1e15-4039-b59f-40cd174315ee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5Mjk4NTEsIm5iZiI6MTcwNzkyOTU1MSwicGF0aCI6Ii8xMDkzMjk3OTIvMzA0ODEyNzA1LTg3MDFhODhkLTFlMTUtNDAzOS1iNTlmLTQwY2QxNzQzMTVlZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQxNjUyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWY0NzllNGY0ZGEyNTViNjViNjEyNDNiZmMyZGM5YzI0YjFhMTFjZGE5ZTYxMTc3OGFmNmNkYTQ1MjdkODQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CzRIsBuPKzIfDIDcwmtn3WVLYIajTfb0IA6uvL6WGqo)
感谢您的特意回复，请确保您本人遵守了《提问的智慧》的前提下冷静思考您的发言，我再次为玩的发言向全体开发者致歉

**Comment by Jason25841** [comment]
我们遭到了你的冒犯，把你反驳的体无完肤很难接受吗？这是受害者有罪论

**Comment by Muska-Ami** [comment]
> 我们遭到了你的冒犯，把你反驳的体无完肤很难接受吗？这是受害者有罪论

差不多了其实没必要这么针锋相对

**Comment by Jason25841** [comment]
> > 我们遭到了你的冒犯，把你反驳的体无完肤很难接受吗？这是受害者有罪论
> 
> 您是怎么定义“虾头”我本人无法定义您的理解，但我解释为无意义语气词玩梗，所以就此作罢我已经道过歉希望您能原谅

无意义的争吵就到此为止

**Comment by Muska-Ami** [comment]
Lock as invaild issues.
