### ISSUE TITLE
[FEAT]: 更直观的Frpc进程管理 Origin: #78

### ISSUE THREAD

**Issue by Muska-Ami** [Muska-Ami/NyaLCF#79]
### 问前检查

- [X] 我确保本功能尚未加入
- [X] 我确保没有其他 Issue 提出此功能

### 功能描述

Transfer from origin #78

**Comment by Muska-Ami** [comment]
@Daiyangcheng 需要frpc或后端提供一个检查隧道状态的接口

**Comment by Daiyangcheng** [comment]
检查隧道本身就存在接口，可以自行查阅 LoCyanFrpPureApp 项目，frps 的路由配置查看路径和返回值格式

**Comment by Daiyangcheng** [comment]
通过BasicAuth方式进行认证，账号密码自行查阅
http://[用户名]:[密码]@[服务器IP]:8233/api/proxy/隧道类型/[用户FrpToken].[隧道名]

**Comment by Daiyangcheng** [comment]
/api/v2/proxies/getStatus

参数：
token 用户 Frp Token
proxy_name 隧道名
proxy_type 隧道类型（tcp。udp）
node_id 节点ID

**Comment by Muska-Ami** [comment]
#101 更新了隧道列表样式

**Comment by Muska-Ami** [comment]
暂时没有计划进一步修改，close.
