### ISSUE TITLE
[BUG]: Windows下无法完全终止进程

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [Muska-Ami/NyaLCF#83]
### 问前检查

- [X] 我在提问之前，已经自己排查过问题
- [X] 我确保我已经搜索了相关资料，但仍无法解决
- [X] 我确保这个 BUG 未曾被报告过
- [X] 我确保这个 BUG 在最新版本可复现

### 问题描述&复现过程

在日志页点击终止所有进程，但是后台frpc并没有关闭，且隧道穿透的内容依然可以正常访问

### 版本

0.1.?

### 运行日志

```sh
无
```

**Comment by whx61** [comment]
#87 我也遇到了这个问题

**Comment by Muska-Ami** [comment]
Fixed.
