### ISSUE TITLE
[BUG]: 无法下载FRPC

### ISSUE THREAD

**Issue by lyjjl** [Muska-Ami/NyaLCF#87]
### 问前检查

- [X] 我在提问之前，已经自己排查过问题
- [X] 我确保我已经搜索了相关资料，但仍无法解决
- [X] 我确保这个 BUG 未曾被报告过
- [X] 我确保这个 BUG 在最新版本可复现

### 问题描述&复现过程

我今天刚刚下载了启动器，但是当我点击设置里面的下载Frpc时，进度条纹丝不动，即使使用镜像源也如此，开VPN也如此

### 版本

0.1.6

### 运行日志

```sh
没有日志
```

**Comment by Muska-Ami** [comment]
@lyjjl 请重启启动器

**Comment by lyjjl** [comment]
重试过多次，无效果



在 2024-02-22 20:23:17，"夏沫花火zzz" ***@***.***> 写道：

@lyjjl 请重启启动器

**Comment by Muska-Ami** [comment]
无法复现你说的情况，请自行排查网络问题

**Comment by Muska-Ami** [comment]
请参考 #60 ，由于无法复现，故关闭。
