### ISSUE TITLE
[BUG]: win任务视图点击“x”关闭软件触发关闭提示叠加

### ISSUE THREAD

**Issue by BaiRuoQiu** [Muska-Ami/NyaLCF#88]
### 问前检查

- [X] 我在提问之前，已经自己排查过问题
- [X] 我确保我已经搜索了相关资料，但仍无法解决
- [X] 我确保这个 BUG 未曾被报告过
- [X] 我确保这个 BUG 在最新版本可复现
- [X] 我确保我已经熟记[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)

### 问题描述&复现过程

win任务视图重复点击“x”关闭软件触发反复弹窗“关闭nyalcf”画面随着点击越来越黑，回到软件则需要多次点击取消

### 版本

0.1.6

### 运行日志

```sh
~
```

**Comment by BaiRuoQiu** [comment]
其实本来想提的不是这个问题来着，是我点击x遇到了窗口变大变高显示异常的问题，但是我到现在都没法复现，看看你们有没有头绪

**Comment by Muska-Ami** [comment]
目前没有复现

> 其实本来想提的不是这个问题来着，是我点击x遇到了窗口变大变高显示异常的问题，但是我到现在都没法复现，看看你们有没有头绪

**Comment by Muska-Ami** [comment]
Fixed.
