### ISSUE TITLE
[BUG]: 登录失败

### ISSUE THREAD

**Issue by huzbin** [Muska-Ami/NyaLCF#89]
### 问前检查

- [X] 我在提问之前，已经自己排查过问题
- [X] 我确保我已经搜索了相关资料，但仍无法解决
- [X] 我确保这个 BUG 未曾被报告过
- [X] 我确保这个 BUG 在最新版本可复现
- [X] 我确保我已经熟记[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)

### 问题描述&复现过程

提示登录失败type ‘String‘ is not a subtype of type ‘int

### 版本

所有版本都是这个问题0.1.6和0.1.7都试过

### 运行日志

```sh
无日志
```

**Comment by Muska-Ami** [comment]
可能是上游API改动导致，会尽快完成修复工作

**Comment by Muska-Ami** [comment]
Fixed.
