### ISSUE TITLE
暗色主题

### ISSUE THREAD

**Issue by Muska-Ami** [Muska-Ami/NyaLCF#9]
新增暗色主题
或允许直接指定主题色种子

**Comment by ltzXiaoYanMo** [comment]
我他妈直接给你反转（？）

**Comment by Muska-Ami** [comment]
> 我他妈直接给你反转（？）

好好好，但是感觉不如加个配置

**Comment by ltzXiaoYanMo** [comment]
> > 我他妈直接给你反转（？）
> 
> 好好好，但是感觉不如加个配置

说的很对，正在实现（

**Comment by Muska-Ami** [comment]
@ltzXiaoYanMo 我在设置加了按钮，你有空写一下SettingPrefs？然后启动的时候默认先读取主题设置，获取配置后再赋值ColorSheme

**Comment by ltzXiaoYanMo** [comment]
> @ltzXiaoYanMo 我在设置加了按钮，你有空写一下SettingPrefs？然后启动的时候默认先读取主题设置，获取配置后再赋值ColorSheme

收到

**Comment by Muska-Ami** [comment]
两个都做了 暗色模式下不能自定义种子，亮色可以

**Comment by Muska-Ami** [comment]
还差开关就完成了

**Comment by Muska-Ami** [comment]
已完成
