### ISSUE TITLE
[FEAT]: 开机自动启动

### ISSUE THREAD

**Issue by Muska-Ami** [Muska-Ami/NyaLCF#98]
### 问前检查

- [X] 我确保本功能尚未加入
- [x] 我确保没有其他 Issue 提出此功能

### 功能描述

允许开机自动启动，允许设置自启动隧道

**Comment by Muska-Ami** [comment]
Done.

**Comment by ltzXiaoYanMo** [comment]
这下世界奇迹了（？）
